// Automatically generated by flapigen
package org.iota.client

/*package*/
internal object JNIReachabilityFence {
    /*package*/
    external fun reachabilityFence1(ref1: Any?)

    /*package*/
    external fun reachabilityFence2(ref1: Any?, ref2: Any?)

    /*package*/
    external fun reachabilityFence3(ref1: Any?, ref2: Any?, ref3: Any?)

    /*package*/
    external fun reachabilityFence4(ref1: Any?, ref2: Any?, ref3: Any?, ref4: Any?)

    /*package*/
    external fun reachabilityFence5(ref1: Any?, ref2: Any?, ref3: Any?, ref4: Any?, ref5: Any?)

    /*package*/
    external fun reachabilityFence6(
        ref1: Any?,
        ref2: Any?,
        ref3: Any?,
        ref4: Any?,
        ref5: Any?,
        ref6: Any?
    )

    /*package*/
    external fun reachabilityFence7(
        ref1: Any?,
        ref2: Any?,
        ref3: Any?,
        ref4: Any?,
        ref5: Any?,
        ref6: Any?,
        ref7: Any?
    )

    /*package*/
    external fun reachabilityFence8(
        ref1: Any?,
        ref2: Any?,
        ref3: Any?,
        ref4: Any?,
        ref5: Any?,
        ref6: Any?,
        ref7: Any?,
        ref8: Any?
    )
}