// Automatically generated by flapigen
package org.iota.client

import kotlin.jvm.Synchronized

class MilestoneUtxoChangesResponse {
    override fun toString(): String {
        run { return this.to_string() }
    }

    override fun equals(obj: Any?): Boolean {
        var equal = false
        if (obj is MilestoneUtxoChangesResponse) equal = obj.rustEq(this)
        return equal
    }

    override fun hashCode(): Int {
        return mNativeObj.toInt()
    }

    private constructor() {}

    private fun to_string(): String {
        return do_to_string(mNativeObj)
    }

    private fun rustEq(o: MilestoneUtxoChangesResponse): Boolean {
        val a0 = o.mNativeObj
        val ret = do_rustEq(mNativeObj, a0)
        //TODO     java.lang.ref.Reference.reachabilityFence(o)
        return ret
    }

    /**
     * Milestone index.
     */
    fun index(): Long {
        return do_index(mNativeObj)
    }

    /**
     * Milestone message id
     */
    fun createdOutputs(): Array<String> {
        return do_createdOutputs(mNativeObj)
    }

    /**
     * Milestone timestamp.
     */
    fun consumedOutputs(): Array<String> {
        return do_consumedOutputs(mNativeObj)
    }

    @Synchronized
    fun delete() {
        if (mNativeObj != 0L) {
            do_delete(mNativeObj)
            mNativeObj = 0
        }
    }

    @Throws(Throwable::class)
    protected fun finalize() {
        try {
            delete()
        } finally {
           // super.finalize()
        }
    }

    /*package*/
    internal constructor(marker: InternalPointerMarker, ptr: Long) {
        check(marker === InternalPointerMarker.RAW_PTR)
        mNativeObj = ptr
    }

    /*package*/
    var mNativeObj: Long = 0

    companion object {
        private external fun do_to_string(self: Long): String
        private external fun do_rustEq(self: Long, o: Long): Boolean
        private external fun do_index(self: Long): Long
        private external fun do_createdOutputs(self: Long): Array<String>
        private external fun do_consumedOutputs(self: Long): Array<String>
        private external fun do_delete(me: Long)
    }
}