// Automatically generated by flapigen
package org.iota.client

import kotlin.jvm.Synchronized

class MqttManager {
    private constructor() {}

    /**
     * Add a new topic to the list.
     */
    fun withTopic(topic: Topic): MqttTopicManager {
        val a0 = topic.mNativeObj
        topic.mNativeObj = 0
        val ret = do_withTopic(mNativeObj, a0)
        val convRet = MqttTopicManager(InternalPointerMarker.RAW_PTR, ret)
        //TODO  java.lang.ref.Reference.reachabilityFence(topic)
        return convRet
    }

    /**
     * Add a collection of topics to the list.
     */
    fun withTopics(topics: Array<Topic>): MqttTopicManager {
        val ret = do_withTopics(mNativeObj, topics)
        return MqttTopicManager(InternalPointerMarker.RAW_PTR, ret)
    }

    /**
     * Unsubscribes from all subscriptions.
     */
    fun unsubscribe() {
        do_unsubscribe(mNativeObj)
    }

    /**
     * Disconnects the broker.
     * This will clear the stored topic handlers and close the MQTT connection.
     */
    fun disconnect() {
        do_disconnect(mNativeObj)
    }

    @Synchronized
    fun delete() {
        if (mNativeObj != 0L) {
            do_delete(mNativeObj)
            mNativeObj = 0
        }
    }

    @Throws(Throwable::class)
    protected fun finalize() {
        try {
            delete()
        } finally {
         //   super.finalize()
        }
    }

    /*package*/
    internal constructor(marker: InternalPointerMarker, ptr: Long) {
        check(marker === InternalPointerMarker.RAW_PTR)
        mNativeObj = ptr
    }

    /*package*/
    var mNativeObj: Long = 0

    companion object {
        private external fun do_withTopic(self: Long, topic: Long): Long
        private external fun do_withTopics(self: Long, topics: Array<Topic>): Long
        private external fun do_unsubscribe(self: Long)
        private external fun do_disconnect(self: Long)
        private external fun do_delete(me: Long)
    }
}